language: python
python:
- "2.7"

# command to install dependencies
install:
  - travis_wait 40 pip install -r requirements.txt
  - pip install coverage

# command to run tests
script:
  - python test_fsttrpgbasicinfo.py

after_success:
    coverage run -m fsttrpgbasicinfo
    pip install codeclimate-test-reporter



