package:
  name: fsttrpgbasicinfo
  version: 0.3.3

build:
 number: 1
 string: alpha

source:
  git_url: https://github.com/Krypticdator/FSTTRPGBasicInfo.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
about:
  summary: Fuzion Roleplayin System basic info